---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-infrastructure.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-infrastructure.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "safe-infrastructure.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "safe-infrastructure.name" . }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- else }}
        resources:
          limits:
            cpu: 2
            memory: 4G
          requests:
            cpu: 1
            memory: 2G
        {{- end }}
        env:
          - name: NGINX_ENTRYPOINT_QUIET_LOGS
            value: "true"
        ports:
        - containerPort: {{ .Values.service.ports.number }}
          name: {{ .Values.service.ports.name }}
          protocol: TCP
        volumeMounts:
          - name: nginx-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-volume
            mountPath: /etc/nginx/html/index.html
            subPath: index.html
          - name: config-volume
            mountPath: /nginx-cfg
          - name: transaction-volume
            mountPath: /nginx-txs
          - name: tmp-volume
            mountPath: /tmp
          - name: cache-volume
            mountPath: /var/cache/nginx
      serviceAccountName: {{ include "safe-infrastructure.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: safe-config
        - name: transaction-volume
          persistentVolumeClaim:
            claimName: safe-transaction
        - name: nginx-volume
          configMap:
            name: {{ include "safe-infrastructure.fullname" . }}-nginx
        - name: tmp-volume
          emptyDir: {} 
        - name: cache-volume
          emptyDir: {} 

